# Ziko909

# docker compose file for running the application

name: inception

services:
# nginx service
 nginx:
  image: nginx:v1
  build:
   context: ./requirements/nginx
  env_file: ./.env
  container_name:  nginx
  networks:
   - inception
  ports:
   - "443:443"
  restart: on-failure
  volumes:
   - wordpress-volume:/var/www/html
  depends_on:
    - wordpress
    - adminer

# wordpress service
 wordpress:
   image: wordpress:v1
   build:
     context: ./requirements/wordpress
   env_file: ./.env
   container_name: wordpress
   networks:
     - inception
   restart: on-failure
   volumes:
     - wordpress-volume:/var/www/html
   depends_on:
     - mariadb
     - redis

# mariadb service
 mariadb:
  image: mariadb:v1
  build:
   context: ./requirements/mariadb
   args:
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     DB_NAME: ${DB_NAME}
     MYSQL_USER: ${MYSQL_USER}
     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  env_file: ./.env
  container_name: mariadb
  networks:
   - inception
  restart: on-failure
  volumes:
   - mariadb-volume:/var/lib/mysql

# adminer
 adminer:
  image: adminer:v1
  build:
    context: ./requirements/bonus/adminer
  env_file: ./.env
  container_name: adminer
  networks:
    - inception
  restart: on-failure
  depends_on:
    - mariadb
  volumes:
    - wordpress-volume:/var/www/html

# static web-site
 static-site:
  image: static-site:v1
  build:
   context: ./requirements/bonus/static-site
  env_file: ./.env
  container_name: static-site
  networks:
   - inception
  ports:
   - "80:80"
  restart: on-failure

  # cadvisor
 cadvisor:
  image: cadvisor:v1
  build:
     context: ./requirements/bonus/cadvisor
  env_file: ./.env
  container_name: cadvisor
  networks:
    - inception
  ports:
    - "8080:8080"
  restart: on-failure
  volumes:
   - /:/rootfs:ro
   - /var/run:/var/run:rw
   - /sys:/sys:ro
   - /var/lib/docker/:/var/lib/docker:ro
   - /dev/disk/:/dev/disk:ro
  devices:
   - /dev/kmsg:/dev/kmsg
  privileged: true
 
 # redis
 redis:
  image: redis:v1
  build:
   context: ./requirements/bonus/redis
   args:
    REDIS_HOST: ${REDIS_HOST}
    REDIS_PASSWORD: ${REDIS_PASSWORD}
    REDIS_MAX_MEMORY: ${REDIS_MAX_MEMORY}
  env_file: ./.env
  container_name: redis
  networks:
   - inception
  restart: on-failure

  # ftp
 ftp:
  image: ftp:v1
  build:
   context: ./requirements/bonus/ftp
   args:
    FTP_USER: ${FTP_USER}
    FTP_PASSWORD: ${FTP_PASSWORD}
  env_file: ./.env
  container_name: ftp
  networks:
   - inception
  ports:
   - "1024:21"
  restart: on-failure
  volumes:
   - wordpress-volume:/home/${FTP_USER}
   

# volumes of the services
volumes:
 wordpress-volume:
  driver_opts:
   type: ""
   o: bind
   device: /home/zaabou/data/wordpress
 mariadb-volume:
   driver_opts:
     type: ""
     o: bind
     device: /home/zaabou/data/mariadb

# network of project
networks:
 inception:
  name: inception
  attachable: false
